language: node_js
node_js:
  - "12.1.0"
git:
  submodules: false

before_script:
  - echo "skip"

script:
  - bash transform-ssh-to-http.sh
  - bash init.sh

before_deploy:
  - bash build-website.sh

deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  local-dir: Website/output/
  github-token: $GH_TOKEN
  on:
    branch: master
